### ISSUE TITLE
安装后错误

### ISSUE THREAD

**Issue by emperinter** [yzmcms/yzmcms#15]
![image](https://user-images.githubusercontent.com/20177836/58246393-882aab00-7d89-11e9-87c7-0d35fa3d21f8.png)

**Comment by yzmcms** [comment]
PHP7取消了MySQL链接驱动，需配置系统的驱动类型为：PDO或者MYSQLI，YzmCMS安装教程：http://www.yzmcms.com/doc/anzhuang.html

**Comment by emperinter** [comment]
thanks！

袁志蒙 <notifications@github.com> 於 2019年5月24日 週五 00:17寫道：
