### ISSUE TITLE
说是开源软件，安装完又要叫买授权 怕了你们这些套路了

### ISSUE THREAD

**Issue by 17isme** [yzmcms/yzmcms#16]

**Comment by ghost** [comment]
开源只是源码公开，不代表免授权，更不代表免费使用。

**Comment by yzmcms** [comment]
> _No description provided._

楼主恐怕没明白开源和免费的区别，开源不等于免费！！
还有一点就是YzmCMS针对个人用户是免费使用的，个人用户只要保留YzmCMS版权信息就可以永久免费使用，只有商业用途才需要购买授权，商业购买授权也是为了软件能够更加长久的发展！
我们从来没有套路，感觉不合适可以用其他系统！
