### ISSUE TITLE
请修改贵CMS相关介绍

### ISSUE THREAD

**Issue by nilcay** [yzmcms/yzmcms#38]
贵CMS存在多处虚假宣传的问题，损害同行的利益。请严谨用辞。
１.你无法证明你是体积最小的，很多CMS只有几百KB不到１M。
２.你无法证明你的CMS“系统运行速度、源码质量都秒杀其他程序”。我粗略看了一下，即发现yzmcms存在很多不合理或不严谨的地方。举例：
核心函数中，getip()最后的正则，直接会导致无法获取IPV6地址。get_address()中出现中文，虽然不是不可以，但这样会拉低档次；函数使用的接口是非可控的外部地址，作为核心函数是非常不严谨的，一旦外部地址失效，核心函数即失效，并增加运行等待时间。

**Comment by nilcay** [comment]
又看了一下，发现你很多函数中都使用了中文。而你的系统中又是带有语言包的。这样就意味着一个问题，你的系统在多语言时，存在输出外文有缺陷的问题，因为由函数返回的字符串直接就固定了是中文。

**Comment by nilcay** [comment]
安全性方面，我并没有测试。但看到其它人有贴出md5加密的函数。这个加密没有考虑为每个站生成不同的加密字串，字串是可以通用的。虽然目前没有人注入成功，但不代表是绝对安全的。

**Comment by yzmcms** [comment]
这位兄台，你可能是误会了吧？
我从来没有说过我的cms是体积最小的呀？
我只想做一个好用的开源的CMS系统，真没想到过会触动同行的利益，CMS介绍我已经修改了，请不要在恶语相加了。
大家都是公开做cms的，也请你不要用小号来污蔑我的系统吧？
