### ISSUE TITLE
XSS vulnerability exists in member submission function

### ISSUE THREAD

**Issue by mntn0x** [yzmcms/yzmcms#42]
会员投稿功能，使用如下payload即可造成xss
`<img+src%3d1+onpointerout%3dalert(1)>`
直接在请求包的content中加上payload，等待审核通过即可。当鼠标滑过图片然后又划出的时候即触发xss
![](https://s2.ax1x.com/2020/03/04/3oQZ4J.jpg)
我在官方演示站投稿了一个文章，id=104，请确认。

-----
Member submission function, using the following payload can cause xss
`<img+src%3d1+onpointerout%3dalert(1)>`
Add the payload directly to the content of the request package and wait for approval. Xss is triggered when the mouse rolls over the picture and then draws out
![](https://s2.ax1x.com/2020/03/04/3oQZ4J.jpg)
I submitted an article on the official demo station, id = 104, please confirm.

**Comment by yzmcms** [comment]
感谢指出，下一个版本将会修复这个问题
