### ISSUE TITLE
连接mysql错误

### ISSUE THREAD

**Issue by h00ls** [yzmcms/yzmcms#51]
github下载下来，放入phpstudy中就报错：Can` not connect to MySQL server!  是什么情况？

**Comment by h00ls** [comment]
![img](https://github.com/unihac/picGo/blob/master/images/1.png?raw=true)

**Comment by myxss** [comment]
<img width="1029" alt="image" src="https://github.com/yzmcms/yzmcms/assets/33475775/e9d3e193-3dc9-438e-b2e8-c7ba390532dd">
