### ISSUE TITLE
 There are SSRF vulnerabilities in background collection management

### ISSUE THREAD

**Issue by BLL-l** [yzmcms/yzmcms#53]
Log in the background management and create a new node in the collection management

![image](https://user-images.githubusercontent.com/64850343/102096574-d584d680-3e5f-11eb-9ce8-f3ae93cf0776.png)
![image](https://user-images.githubusercontent.com/64850343/102096606-de75a800-3e5f-11eb-967b-e42d715687a8.png)

Add our url with the attack code

![image](https://user-images.githubusercontent.com/64850343/102096962-41ffd580-3e60-11eb-826b-02aba806b0e1.png)
![image](https://user-images.githubusercontent.com/64850343/102097004-504df180-3e60-11eb-8034-760c6e4e8578.png)

Then click collect

![image](https://user-images.githubusercontent.com/64850343/102097068-68be0c00-3e60-11eb-9564-db6b328976ce.png)

Because two methods are written in the source code
If you have curl extensions, use curl_ Close function. If not, use file_ get_ Contents function

![image](https://user-images.githubusercontent.com/64850343/102097390-cc483980-3e60-11eb-8aff-979d182da035.png)

And when processing the URL, only the first four characters of the URL are obtained by using the substr function, and whether it is HTTP is judged. If it is, it is checked

![image](https://user-images.githubusercontent.com/64850343/102097668-2b0db300-3e61-11eb-9786-8435cf153188.png)

Here, you can use the features of PHP. When PHP encounters an unknown protocol, it will throw a warning and set the protocol to null. When the Protoco is null or file, the local operation will be carried out. By default, the local file operation will be performed if the protocol is not transferred or the protocol does not exist.

Therefore, we can use a custom protocol, such as httpxxx, which can start from HTTP, but can't be HTTPS.
We can try to read the /etc/passwd file

![image](https://user-images.githubusercontent.com/64850343/102098131-c69f2380-3e61-11eb-92d1-5ff4f67f9c05.png)

Then click collect

![image](https://user-images.githubusercontent.com/64850343/102098223-e6364c00-3e61-11eb-9814-47f6eb309ff2.png)

The file was read successfully

**Comment by yzmcms** [comment]
Thank you. It's fixed
