### ISSUE TITLE
YzmCMS V5.8 XSS bug

### ISSUE THREAD

**Issue by hackxiaofeng** [yzmcms/yzmcms#54]
Hi, I would like to report Cross Site Scripting vulnerability in YzmCMS V5.8

Description:
In the content.class.php row 42, No filtering of the searinfo parameterA xss vulnerability was discovered in yzmcms.
In YzmCMS v5.8, stored XSS exists via the /admin/system_manage/user_config_edit.html value parameter, which allows remote attackers to inject arbitrary web script or HTML.
![图片](https://user-images.githubusercontent.com/17332952/103343590-65b15580-4ac7-11eb-96d4-77223e5e0323.png)
![图片](https://user-images.githubusercontent.com/17332952/103343632-7e217000-4ac7-11eb-89bd-ebf68e220198.png)
![图片](https://user-images.githubusercontent.com/17332952/103343647-84175100-4ac7-11eb-9058-80ee213c3de2.png)
![图片](https://user-images.githubusercontent.com/17332952/103343670-8c6f8c00-4ac7-11eb-9da2-3c9076722929.png)

**Comment by yzmcms** [comment]
The cookie is read-only
