### ISSUE TITLE
YzmCMS V6. 3. There are concurrent operations in the front desk of the official version.(YzmCMS V6.3 正式版前台存在可并发操作。)

### ISSUE THREAD

**Issue by zpxlz** [yzmcms/yzmcms#61]
Prepare an account test01, comment at the bottom of an article, and grab the request package,
![image](https://user-images.githubusercontent.com/89461075/150621837-edf5796c-4954-4b74-8b9b-e58d9f6bd4e9.png)

Send to repeater,
![image](https://user-images.githubusercontent.com/89461075/150621849-0020dd7d-776a-4271-a699-b47addc3d7dc.png)

Manually send several times, you can batch brush malicious comments.
![image](https://user-images.githubusercontent.com/89461075/150621880-c3b40211-aed4-448c-95d8-134b48a36645.png)

**Comment by yzmcms** [comment]
下个版本修复

**Comment by jaylan545** [comment]
> 下个版本修复

这不是并发，如果多发送几次就算并发那就是个笑话

**Comment by yzmcms** [comment]
这是来自QQ邮箱的自动回复邮件。你好，您的邮件我收到了，我会尽快给你回复。
