### ISSUE TITLE
XSS vulnerabilities exist on the YzmCMS 7.0 debugging mode message interface

### ISSUE THREAD

**Issue by aaALKing** [yzmcms/yzmcms#65]
1、利用前提：开启调试模式，APP_DEBUG为true
     Usage prerequisite: Enable debugging mode and set APP_DEBUG to true

2、若管理员未开启会员注册，访问 member/index/register.html 
      if the administrator has not open membership registration, access to the member/index/register.html

![c26551cb3477176637177e408d2bacf](https://github.com/yzmcms/yzmcms/assets/136289683/bcd3a2cc-57af-4084-ae7e-6addd51bcd87)

      抓包修改Referer，点击返回上一页
      Capture packet to modify Referer, successful pop-up window
a、修改为javascript:alert('xss')，成功弹窗
a. Change to javascript:alert('xss') and click to return to the previous page
      
![28a71031782d1888e7060839ca4290c](https://github.com/yzmcms/yzmcms/assets/136289683/65d07145-aa31-42bb-b0d5-90a5de2b4193)
![2656a79b5fc719d3f3df767288acddb](https://github.com/yzmcms/yzmcms/assets/136289683/31b2decd-627b-439a-8eed-ba05a8f333b8)

b、url跳转，修改为https://www.baidu.com，成功跳转到百度
b. modify to https://www.baidu.com, successfully jump to Baidu

![c2f6b5e4174d51b881b12a0c7886c33](https://github.com/yzmcms/yzmcms/assets/136289683/c8718a26-b2bc-4b3e-85a7-aa7df051f8f9)
![b5748d07ecc0e561679d8fc4b56967b](https://github.com/yzmcms/yzmcms/assets/136289683/53ebf16c-5ad5-42f6-b797-ac1df863f948)
![36c75af92c0d038aef2276dbd6f3775](https://github.com/yzmcms/yzmcms/assets/136289683/9c861d29-f6df-49cb-9fec-d184f86d1b5d)

3、经测试，像这样的所有提示信息界面均存在此漏洞
3, after testing, all the prompt information interface like this has this vulnerability

**Comment by yzmcms** [comment]
感谢反馈，已修复

**Comment by mayylu** [comment]
这个漏洞根本利用不了，js是无法修改http的refer字段的

**Comment by yzmcms** [comment]
这是来自QQ邮箱的自动回复邮件。你好，您的邮件我收到了，我会尽快给你回复。
