### ISSUE TITLE
YzmCMS V5.2  XSS bug

### ISSUE THREAD

**Issue by dreamsroid** [yzmcms/yzmcms#8]
Hi, I would like to report Cross Site Scripting vulnerability in YzmCMS V5.2.

Description:
Cross-site scripting (XSS) vulnerability in  search pages  and  you can inject arbitrary web script or HTML via the multiple parameters.

In the   content.class.php  row 42, No filtering of the searinfo parameter
![image](https://user-images.githubusercontent.com/20120056/48209427-1f14b480-e3b0-11e8-9682-bc291ca2a54e.png)

Steps To Reproduce:
1.login to administrator panel.
2.Open below URL in browser which supports flash.
url:http://192.168.127.130/yzmcms/admin/content/search.html?m=admin&c=content&a=search&modelid=1&catid=0&start=&end=2018-11-08&flag=0&status=99&type=1&searinfo={xsspayload}&dosubmit=1
eg:
xsspayload="><script>alert(1)</script>
![_20181108233531](https://user-images.githubusercontent.com/20120056/48209013-18397200-e3af-11e8-84e1-7afaafc743d1.png)

![_20181108233546](https://user-images.githubusercontent.com/20120056/48209866-238d9d00-e3b1-11e8-98c2-f1f57f43d2c8.png)

Fix:
Filter the searinfo parameter

**Comment by yzmcms** [comment]
在后台这样搞，好像没啥用吧
